### ISSUE TITLE
Text Collision when defaultValue supplied

### ISSUE THREAD

**Issue by JBaczuk** [callstack/react-native-paper#1072]
## Environment

using master branch https://github.com/callstack/react-native-paper/commit/b1cb7288f9742a2c4bdeff9e04e7cf826abf285e

## Description

When a `defaultValue` is supplied to the 'outlined' `<TextInput>` component, and it is not in focus, the label and defaultValue collide.

<img width="328" alt="Screen Shot 2019-05-17 at 3 30 03 PM" src="https://user-images.githubusercontent.com/8162417/57957324-22d24800-78b9-11e9-85ad-2b35a1d2e24f.png">

## Reproducible Demo

```
<TextInput
    style={{ flex: 1 }}
    label='Name'
    defaultValue={'21535278'}
    onChangeText={name => {
        // do something
    }}
    mode={'outlined'}
/>
```

**Comment by jbinda** [comment]
Hello JBaczuk,

Thanks for sending PR.

The issue is already fixed in 3.0 branch with #1068

Regards

**Comment by Hektar90** [comment]
Hi,

I am using react-native-paper : 4.5.0

and the issue still persists

<img width="340" alt="Bildschirmfoto 2021-02-26 um 18 30 23" src="https://user-images.githubusercontent.com/15243732/109334324-df17bb00-7860-11eb-9368-37392d876eb0.png">

<img width="304" alt="Bildschirmfoto 2021-02-26 um 18 31 05" src="https://user-images.githubusercontent.com/15243732/109334367-e9d25000-7860-11eb-8b33-6f34a62bbf09.png">
