### ISSUE TITLE
React-Native 0.61.x

### ISSUE THREAD

**Issue by marcorm** [callstack/react-native-paper#1341]
## Environment

Android API Level 26
RN 0.61.x
react-native-paper stable and alpha

## Description

I noticed a problem with [react-native-paper](https://github.com/callstack/react-native-paper) and **react-native 0.61.x** on **Android API Level 26**.
Doesn't happen on API Level 23 or 29.

When i open a `Dialog` inside a `Portal` it shows up weird.
Same problem with FAB.

The problem doesn't arise with RN 0.60.5.
It happens with the last versions of react-native-paper (stable and alpha).

Here are two attachments showing the issue:
RN 0.60.5
<img src="https://user-images.githubusercontent.com/2567466/65372403-1d727900-dc70-11e9-9097-432a795dcacc.png" width="250" height="500">
RN 0.61.x
<img src="https://user-images.githubusercontent.com/2567466/65372442-a5f11980-dc70-11e9-895b-86643fe42050.png" width="250" height="500">

P.S. don't pay attention to Icons in the bottom tab.

## Reproducible Demo

Just start a new project with RN 0.61.x and put a FAB or a Portal inside it with **react-native 0.61.x** on **Android API Level 26**.

EDIT: [Repository to reproduce the issue](https://github.com/marcorm/rn061_rnp_issue/tree/master)

P.S. I don't know if its RN issue or a RNP issue.
I also posted it here:
https://github.com/react-native-community/releases/issues/140#issuecomment-533790202

**Comment by abdullah-sr** [comment]
running into the same issue on Android

**Comment by marcorm** [comment]
I know it's not a `react-native-paper` issue but, as stated [here](https://github.com/facebook/react-native/issues/26544) setting `borderRadius` to `undefined` solves the problem.

**Comment by Ludus-Team** [comment]
It's not just on dialog, it's happen on Android with elevation View (Upgrade to 0.61.0 and still the same problem)

With 0.60.5:
![Screenshot_1569395991](https://user-images.githubusercontent.com/35457731/65578384-63845100-df7e-11e9-99aa-83d3de45f741.png)

With 0.61.0:
![Screenshot_1569396036](https://user-images.githubusercontent.com/35457731/65578377-5f583380-df7e-11e9-9d92-69aebb6faa62.png)

**Comment by usmansbk** [comment]
Facing the same problem with <Fab/>

**Comment by slavikdenis** [comment]
Might be related to https://github.com/facebook/react-native/issues/26544

**Comment by gdoudeng** [comment]
I am facing this problem and hope to solve it as soon as possible.

**Comment by carlosroberto555** [comment]
+1 Same issue with FAB

**Comment by satya164** [comment]
https://github.com/facebook/react-native/pull/26682

**Comment by satya164** [comment]
Fixed in RN 0.61.2 https://github.com/facebook/react-native/releases/tag/v0.61.2

**Comment by marcorm** [comment]
Great

**Comment by deadcoder0904** [comment]
Hey, @satya164 I am still getting this error. I'm on v0.61.2 👇

![bug icon](https://user-images.githubusercontent.com/16436270/66291754-3a5dac00-e900-11e9-8734-78ca3a4d5da1.png)

I've also opened an issue on RN 👉https://github.com/facebook/react-native/issues/26740 which contains the repro steps

**Comment by zcmgyu** [comment]
Confirmed still get error on React Native 0.61.5

**Comment by todorone** [comment]
@satya164 This issue is still around with latest RN versions, please reopen it...
