### ISSUE TITLE
TouchableRipple ripple effects starts from the wrong location

### ISSUE THREAD

**Issue by jHorovitz** [callstack/react-native-paper#2386]
Pressing a TouchableRipple sometimes starts the ripple effect from the wrong location

TouchableRipple should start from where the button is pressed.

https://snack.expo.io/gicfPGsuQ

Sorry I don't know how to make a video with where I press on my android phone. Happy to help out with this if you have instructions on how to do this. This is pretty easy to recreate by pressing alternating corners of the button. You will notice that the ripple sometimes comes out of the previous location.

### What have you tried

I don't think the environment is relevant as this is reproducible in a snack.

| software              | version
| --------------------- | -------
| ios or android        | android Pixel 3 running expo client 2.17.5
| react-native          | 0.63.3
| react-native-paper    | 4.4.1
| node                  | 15.2.1
| npm           | 6.14.9
| expo              | 39.0.5
|react-native-vector-icons|7.1.0

https://snack.expo.io/gicfPGsuQ

**Comment by jHorovitz** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-paper`
> * `react-native-vector-icons`
> * `expo`
> * `npm`
> * `yarn`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

updated

**Comment by mikelpr** [comment]
I came here to report this

**Comment by mikelpr** [comment]
no solution and no workaround, waiting for it to be fixed in the library.

**Comment by Hatyman** [comment]
same issue. Looks like it updates touch position after ripple, but expected before animation.

**Comment by intergalacticspacehighway** [comment]
Created a PR for the fix - https://github.com/facebook/react-native/pull/31777

**Comment by intergalacticspacehighway** [comment]
This has been fixed and released in react native 0.66. 🥳

**Comment by ashuvssut** [comment]
There are 2 possible fixes:
- It happens when you havn't kept your button children wrapped inside a single `View`. The `View` wrapper should be the only childe of your `TouchableRipple`
- Still not fixed? use `TouchableNativeFeedback` from `react-native-gesture-handler`
