### ISSUE TITLE
iOS 14.2 - UI goes to 10 fps when TextInput secureTextEntry=true

### ISSUE THREAD

**Issue by VictorioMolina** [callstack/react-native-paper#2433]
### Current behaviour

The app goes too slow when I start typing in a form with a textinput for passwords.

### Expected behaviour

No lag.

### Code sample
```
import React from "react"
import { View } from "react-native"
import { TextInput, useTheme } from "react-native-paper";

export default function App()  {
   return (
     <View>
        <TextInput
            placeholder="Email or username"
            maxLength={50}
          />

          <TextInput
             placeholder="Password"
             maxLength={30}
             secureTextEntry={true}
          />
      </View>
   )
}
```

### What have you tried
If I set secureTextEntry to false, all works fine.

### Your Environment

| software              | version
| --------------------- | -------
| ios                         | 14.2
| react-native          | ^0.63.3
| react-native-paper    | ^4.5.0
| node                  | 12.18.1
| yarn           |  1.22.4
| expo sdk              | 39.0.0

**Comment by VictorioMolina** [comment]
Solved with iOS 14.4

**Comment by Oleksii27** [comment]
@VictorioMolina what to do on iOS <14.4?

**Comment by Seriosus** [comment]
I'm using iOS 17.1 and this performance issue is still on even latest expo/rn version.

The funny thing is when `secureTextEntry` is true, performance goes insanely low, till there are some count of chars on the text input, like 15 or 14 chars, then performance is fine, but if I delete chars to be lower than 15 or 14 chars again goes the low performance, even deleting the whole value at once, massively low performance again.

If I set `secureTextEntry` to false, then problem is gone at all.

**Comment by dwolrdcojp** [comment]
I can confirm experiencing the same thing with secureTextEntry set to true on iOS 17.4.1 and latest expo go v 2.30.10

**Comment by Bialson** [comment]
Also here, I'm experiencing this in the latest iOS version and Expo SDK 51 with dev client

**Comment by felippewick** [comment]
I experience the same 
    "react-native": "0.74.3",
    "expo": "51.0.22",
