### ISSUE TITLE
Icons do not work in Expo SDK 40

### ISSUE THREAD

**Issue by actuallymentor** [callstack/react-native-paper#2450]
### Current behaviour

Icons are not rendering in Expo projects. [See this snack](https://snack.expo.io/@mentor/broken-react-natve-paper).

### Expected behaviour

Icons to display when used.

### Code sample

[See this snack](https://snack.expo.io/@mentor/broken-react-natve-paper).

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/9071382/102628356-d52f5880-4149-11eb-8ff0-c38a653e7415.png)

### What have you tried

Tried in existing expo project, new expo project and in snack.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | latest
| react-native          | 0.63
| react-native-paper    | 4.5.0
| node                  | 14
| expo sdk              | 40

**Comment by actuallymentor** [comment]
react-native: `0.63.x`
react-native-vector-icons: `7.1.0`
expo: `40.0.0`

**Comment by ravikantmishra** [comment]
For me also icons are not working in android but it's working fine on the web. 

Earlier It was throwing an error. Unable to resolve "`react-native-vector-icons/MaterialCommunityIcons`" from "`node_modules\react-native-paper\src\components\MaterialCommunityIcon.tsx`". But afterinstaling `react-native-vector-icons` error is gone still icons are showing as "cross icon".

**Comment by actuallymentor** [comment]
> For me also icons are not working in android but it's working fine on the web.

Interesting, I can confirm the icons do work on web.

> But afterinstaling react-native-vector-icons error is gone still icons are showing as "cross icon".

Exactly the behaviour I am seeing.

**Comment by raajnadar** [comment]
This should resolve the problem https://github.com/oblador/react-native-vector-icons#the-icons-show-up-as-a-crossed-out-box-on-android

**Comment by actuallymentor** [comment]
> This should resolve the problem oblador/react-native-vector-icons#the-icons-show-up-as-a-crossed-out-box-on-android

Thanks for the breadcrumb!

This is a manual fix for a structural problem. The previous implementation worked, and this one fails.

Besides, `expo` projects can't be fixed that way.

**Comment by actuallymentor** [comment]
About a month later I'm still experiencing this breaking issue. Does anyone have a suggested fix for Expo that doesn't require manual file transfers or edits?

**Comment by actuallymentor** [comment]
I'm not sure what the issue was, but I solved it by:

0. Use `"@expo/metro-config"` in `metro.config.js`
1. Removing `react-native-vector-icons` from the `package.json`
2. Updating all packages to their newest known compatible versions
3. Deleting `node_modules` and `package-lock.json`
4. Reinstalling dependencies

Closing this since my issue was resolved, but hope others experience the same.

**Comment by varunsingh3000** [comment]
I had the same issue, I didnt try the solution by @actuallymentor. They seem to have changed the way we declare the required icons. (https://docs.nativebase.io/docs/GetStarted.html)

import { Ionicons } from '@expo/vector-icons';

async componentDidMount() {
    await Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
      ...Ionicons.font,   //(Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf") previous way
    });
    this.setState({ isReady: true });
  }

This worked for me. I know the issue is closed but this might help too.

**Comment by nonameolsson** [comment]
Yeah, I have been struggling with this problem the last days. After much debugging I think I found the problem.

The solution was very simple. I have a `babel.config.js`, and had to add ` "babel-preset-expo"` to `presets`.

After that I removed `node_modules`, `.expo` and `yarn.lock`. After that I installed modules with `yarn` and then started the packager with `expo start -c`. 

`babel.config.js`

```js
module.exports = {
  presets: ["module:metro-react-native-babel-preset", "babel-preset-expo"],
  env: {
    production: {},
  },
  plugins: [
    [
      "@babel/plugin-proposal-decorators",
      {
        legacy: true,
      },
    ],
    ["@babel/plugin-proposal-optional-catch-binding"],
  ],
}

```
