### ISSUE TITLE
When textinput is autofilled upon loading a page, the textinput label is still in the placeholder place until clicking on the textinput

### ISSUE THREAD

**Issue by Rubenvdveen** [callstack/react-native-paper#2764]
### Current behaviour

When textinput is autofilled upon loading a page, the textinput label is still in the placeholder place until clicking on the textinput

### Expected behaviour

The label should be in the right spot upon getting autofilled

### Code sample

`<TextInput mode="outlined" label={"Email address"} />`

### Screenshots (if applicable)

<img width="482" alt="Screenshot 2021-06-07 at 12 27 35" src="https://user-images.githubusercontent.com/22151095/121002133-4e6c4780-c78c-11eb-8bd1-f6a2ad800399.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |-
| react-native          | 0.64.2
| react-native-paper    |4.9.1
| node                  |v15.5.1
| npm or yarn           | 1.22.10
| react-native-web              | 0.16.3

**Comment by shujathkhan** [comment]
@Rubenvdveen @brunohkbx If this issue is still up for grabs, happy to contribute to it.

**Comment by Rubenvdveen** [comment]
@shujathkhan it is! Be my guest

**Comment by shujathkhan** [comment]
@Rubenvdveen Can you share which platform and the version, did you find this bug in ? If possible a repro would be helpful.

**Comment by Rubenvdveen** [comment]
@shujathkhan This happens on web. I'm using Chrome with Chrome passwords to autofill the fields (with the blue box).  I don't have time right now to make a repro, but you should be able to repro it. 

If not, please let me know and I'll create one later.

**Comment by brunohkbx** [comment]
@shujathkhan Take a look at this #2850. I fixed it for `flat` mode but `outlined` is a bit tricky and I couldn't find a way to fix it.

**Comment by avzz-19** [comment]
Any update on this issue? It is still happening in 'outlined' mode.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/87358607/225514407-02a67717-7c4b-42a7-ac90-bb02e282be57.png">
