### ISSUE TITLE
KeyboardAvoidingView not working with header and material-bottom-tabs on iOS

### ISSUE THREAD

**Issue by raajnadar** [callstack/react-native-paper#3272]
Reported on react-navigation https://github.com/react-navigation/react-navigation/issues/10583

OP solved it by switching to bottom tabs so it seems the issue lies in the material bottom tabs from paper https://stackoverflow.com/a/72561415/5519872

### Current behaviour

KeyboardAvoidingView does not avoid the keyboard correctly, if you use a header and material-bottom-tabs on iOS. For Android, everything works out of the box.

### Expected behaviour

It should obviously avoid the keyboard.

### Code sample

https://github.com/tomwaitforitmy/keyboardAvoidingViewAndNavigation

https://snack.expo.dev/@tomwaitforitmy/keyboardavoidingview

### Your Environment

| software              | version
| --------------------- | -------
| ios        |  N/A
| react-native          | 0.68.1
| react-native-paper    | 4.12.3
| node                  | 16.13.1
| npm or yarn           | 1.22.19
| expo sdk              | 45.0.0

**Comment by tomwaitforitmy** [comment]
>     react-native (found: 0.68.1, latest: 0.69.2) 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

According to [documention](https://docs.expo.dev/versions/latest/) Expo SDK would only be compatible with react-native 0.68.2

**Comment by raajnadar** [comment]
It is a bot you can ignore that, next Expo SDK will support RN 0.69.3 which is the latest version, It will be available today or tomorrow

**Comment by lukewalczak** [comment]
Fixed via: https://github.com/callstack/react-native-paper/pull/3316. Will be released in `5.0.0-rc.5`

**Comment by tomwaitforitmy** [comment]
@lukewalczak I recently updated my minimal not working example to react-native-paper 5.2.0. See here:
https://snack.expo.dev/@tomwaitforitmy/keyboardavoidingview

The bug is still there. Did I do anything wrong or did you not fix it?
