### ISSUE TITLE
React Native V0.71.0 Shadow Warnings

### ISSUE THREAD

**Issue by stakez** [callstack/react-native-paper#3593]
### Current behaviour
Since upgrading to React Native 0.71.0, the following warning has been occurring
` WARN  (ADVICE) View #1853 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.`

After removing several React Native paper Components (especially Surface), the warnings dropped. After reverting to original, the warnings all return. 

### Expected behaviour
No warning should be shown.

### How to reproduce?
Run a React Native App using  V0.71.0 and view the terminal running `react-native start`

### Preview

![Screenshot 2023-01-12 at 1 37 48 PM](https://user-images.githubusercontent.com/99569934/212186665-d86cdcac-a5f3-4dd1-80cf-6306aee1b291.png)

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                |0.71.0
| react-native-paper    | ^5.1.2
| node                            | 18.12.1
| npm or yarn                | yarn
| expo sdk                     | not applicable

**Comment by lukewalczak** [comment]
As you noticed the issue comes form the `Surface` component where we are applying the elevation, but the views don't have a specified background color, that's why the warning appears. I will definitely check what we can do about it.

**Comment by stakez** [comment]
Thanks @lukewalczak. Looking toward to what you find.

**Comment by Yusk03** [comment]
Can agree
Have the same problem, hope you'll resolve it

**Comment by asurare** [comment]
Having the same issue after a recent update. Is it open to PR ?

**Comment by lukewalczak** [comment]
>  Is it open to PR ?

Sure, contributions are welcomed!

**Comment by visoft** [comment]
This is happening with the Portal and Dialog components as well.

**Comment by Streudal** [comment]
Adding on to what @visoft mentioned: this is also happening with the FAB component as well. Basically anything that has a shadow built in it seems like.

**Comment by lukewalczak** [comment]
We are aware of that issue and there is a [PR](https://github.com/callstack/react-native-paper/pull/3738) which should fix the warning.

**Comment by lukewalczak** [comment]
Version `5.5.0` has been released and the issue should be fixed :)

**Comment by Streudal** [comment]
Everything is lookin great! Thanks for the updates!

**Comment by ericpoulinnz** [comment]
@lukewalczak I'm still getting this warning in `5.5.2`. 

Seems to be the `AnimatedFAB`.

**Comment by spaskhalov** [comment]
I'm getting this warnings, after setting buttonColor for Button.

**Comment by CarlosSLoureiro** [comment]
someone know to ignore this warning from console/terminal?

**Comment by lukewalczak** [comment]
> I'm getting this warnings in 5.5.2, after setting buttonColor property for Button.

I was not able to reproduce it unfortunately with the `Button`

> Seems to be the AnimatedFAB.

Correct, there is still the warning in `AnimatedFAB`, which is related to the component composition and its animation – it depends on `transparent` background color in the wrapper container, which triggers the warning. We are aware of that and will check what we can do about it.

> someone know to ignore this warning from console/terminal?

The log is printed from `react-native` using `RCTLogAdvice` and I think there is not way to suppress it.

**Comment by ericpoulinnz** [comment]
> We are aware of that and will check what we can do about it.

@lukewalczak is this something actively being investigated?

> The log is printed from `react-native` using `RCTLogAdvice` and I think there is no way to suppress it.
I am handing over a project to a client with a technical person onboard and they are giving me grief about any warnings in the console. Suppressing is both challenging and now that they have seen the warning, potentially not viable for me.

**Comment by mertkahramanturk** [comment]
This error requires you to specify the background color of the element you want to shade.something like that: 
        backgroundColor: colors.white,
        shadowColor: '#171717',
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 0.3,
        shadowRadius: 5,

**Comment by fellenabmb** [comment]
This issue is still present. And just as the author, I narrowed it down to the Surface component.

<img width="1378" alt="image" src="https://github.com/callstack/react-native-paper/assets/69863090/14ff04ff-8eef-4491-8ba1-6697f3c24506">

Currently using:

```
    "react-native": "0.72.4"
    "react-native-paper": "^5.8.0"
```

**Comment by RuslanLeafio** [comment]
This issue is still present

react-native: 0.72.4

**Comment by brunoravizzinidev** [comment]
react-native: 0.71.8
react-native-paper: 5.10.0

This issue is present, I'm seeing it in the AnimatedFAB

**Comment by ramakula** [comment]
We are also seeing this:

 WARN  (ADVICE) View #46655 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
 WARN  (ADVICE) View #46653 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
 WARN  (ADVICE) View #48305 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
 WARN  (ADVICE) View #48303 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.

**Comment by ndekross** [comment]
I'm experiencing the same issue using the react-native-drop-shadow library to create stacked shadows. This doesn't affect perceived performance on iOS devices and I'm unsure how to handle this unsolicited "ADVICE". It fills up the console and there's no apparent way to silence it. `LogBox` ignoring doesn't work either.

**Comment by Fortidude** [comment]
Im seeing this as well. Any way to ignore / silence it?

**Comment by CostasCF** [comment]
Did you find any way to silence it?

**Comment by JeanBaptisteBolh** [comment]
@Fortidude @CostasCF I am also looking for a way to silence this.

**Comment by Abdeldmh** [comment]
Still no fix for this ??

**Comment by abubakar2000** [comment]
Im using this version `"react-native-paper": "^5.11.6"` and still facing this issue.

**Comment by Abdeldmh** [comment]
Hi ! I've finally identified the issue. Initially, I thought it might be related to `react-native-paper`, but after explore other possibilities. It turns out that when you set `backgroundColor: 'transparent'`, it triggers the warning. The solution? I added `shadowColor: 'transparent'`, and voila, the issue was resolved! 😄

**Comment by R4tch3t** [comment]
> Hi ! I've finally identified the issue. Initially, I thought it might be related to `react-native-paper`, but after explore other possibilities. It turns out that when you set `backgroundColor: 'transparent'` on some components like Views, it triggers the warning. The solution? I added `shadowColor: 'transparent'`, and voila, the issue was resolved! 😄

not work :/

**Comment by R4tch3t** [comment]
only adding the backgroundColor to the elevated component :/

**Comment by fellenabmb** [comment]
This issue is still present!.

**Comment by JuMaruhn** [comment]
If you do not need the functionalities of the Surface component, you can go to the AnimatedFAB.tsx and replace the `<Surface>` component by a `<Animated.View>` component.

**Comment by devonik** [comment]
For me it was the elevated style of a react-native-elements Icon. 
<Icon raised />
When I remove the raised the warning it's gone

**Comment by smidlma** [comment]
In case of Modal you have to set solid color to container bg to dismiss the warning:
```jsx
        <Modal visible={visible} onDismiss={hideModal} contentContainerStyle={containerStyle}>
          <Text>Example Modal.  Click outside this area to dismiss.</Text>
        </Modal>
```
see the docs: https://callstack.github.io/react-native-paper/docs/components/Modal/

**Comment by ericpoulinnz** [comment]
This issue seems to be solve now (potentially upstream?)

I upgraded to Expo 53 / RN 79 at the same time as jumping to the later RN Paper version and the warnings have disappeared!
