### ISSUE TITLE
navigationState is showing deprecated

### ISSUE THREAD

**Issue by ananduremanan** [callstack/react-native-paper#4213]
navigationState is showing deprecated with BottomNavigation.Bar. How do I fix this?

My Dependencies

```
"dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.11",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-paper": "^5.11.3",
    "react-native-vector-icons": "^10.0.2"
  },
```
#### Screenshot

![image](https://github.com/callstack/react-native-paper/assets/48993261/ee3897af-c8cf-4511-b9d2-63a627491e4b)

Any other workaround for this?

**Comment by KristampsWong** [comment]
same issues here, anyone fixed it?

**Comment by lukewalczak** [comment]
Please install library version `5.11.4`

**Comment by TobyEalden** [comment]
I'm still seeing this with `5.11.4`

![Screenshot 2023-12-21 at 08 30 32](https://github.com/callstack/react-native-paper/assets/1628365/22ce325c-c8ff-4b05-85db-40e70202f6a7)

![Screenshot 2023-12-21 at 08 31 16](https://github.com/callstack/react-native-paper/assets/1628365/3b90ae1e-b08a-4dc7-b793-5c63ef298b85)

**Comment by amirreza-km** [comment]
I have the same issue now 
How to fix?

**Comment by ananduremanan** [comment]
@amirreza-km it was fixed with the update for me, delete the package from npm module and delete the package lock json as well, then reinstall the package the issue will be gone..

**Comment by amirreza-km** [comment]
> @amirreza-km it was fixed with the update for me, delete the package from npm module and delete the package lock json as well, then reinstall the package the issue will be gone..

I uninstalled and installed again but not fixed!
What version have you installed?

**Comment by algorhythmic92** [comment]
This is not fixed. Even after a `rm -rf node_modules/ && rm package-lock.json && npm install` on 5.12.1, this issue persists:

package.json:
![image](https://github.com/callstack/react-native-paper/assets/149957752/77b54986-5d41-4048-bd30-68b9ccab2787)

Lock file resolved version:
![image](https://github.com/callstack/react-native-paper/assets/149957752/768c7cc8-9653-4963-8229-c2ca9f652824)

Your module:
![image](https://github.com/callstack/react-native-paper/assets/149957752/ef6c29da-c351-4ea9-9675-c43a4cd8c864)
