### ISSUE TITLE
Add customizable icon size for BottomNavigation

### ISSUE THREAD

**Issue by peacechen** [callstack/react-native-paper#455]
### Current behaviour

Icons are fixed at size 24 in BottomNavigation.

### Expected behaviour

Add a prop to support custom icon sizes.

### Code sample

I'm using `react-navigation-material-bottom-tabs` which in turn uses this library.  If I specify icon sizes greater than 24, the labels render in the center of the icon instead of below (see screenshot below).

```
let iconSize = sizes.h2;
let iconContainerStyle = [s.aic, {width: iconSize, height: iconSize}];

this.tabNav = createMaterialBottomTabNavigator(
  {
    Docs: { screen: Docs,
      navigationOptions: {
        tabBarLabel: 'Docs',
        tabBarIcon: ({ tintColor }) => (<View style={iconContainerStyle}><Icon style={[{color: tintColor}]} size={iconSize} name={'document'}/></View>),
        gesturesEnabled: false,
      }
    },
    Add: { screen: Add/>,
      navigationOptions: {
        tabBarLabel: 'Add',
        tabBarIcon: ({ tintColor }) => (<View style={iconContainerStyle}><Icon style={[{color: tintColor}]} size={iconSize} name={'add'}/></View>),
        gesturesEnabled: false,
      }
    },
    Search: { screen: Add/>,
      navigationOptions: {
        tabBarLabel: 'Search',
        tabBarIcon: ({ tintColor }) => (<View style={iconContainerStyle}><Icon style={[{color: tintColor}]} size={iconSize} name={'search'}/></View>),
        gesturesEnabled: false,
      }
    },
    Profile: { screen: Profile,
      navigationOptions: {
        tabBarLabel: 'Profile',
        tabBarIcon: ({ tintColor }) => (<View style={iconContainerStyle}><Icon style={[{color: tintColor}]} size={iconSize} name={'user'}/></View>),
        gesturesEnabled: false,
      }
    },
  },
  {
    initialRouteName: 'Manifest',
    stateName: props.name,
    activeTintColor: lightColors.primaryButtonFontColor,
    inactiveTintColor: lightColors.secondaryColor,
    barStyle: [navBackground, s.h4],
  }
);
```

### Screenshots (if applicable)

<img src="https://user-images.githubusercontent.com/6295083/42716526-8669bb2c-86c1-11e8-9149-b2be31558053.png">

### What have you tried

Different icon sizes.  Only renders properly if icon size is 24, the fixed size set in BottomNavigation.js.
https://github.com/callstack/react-native-paper/blob/master/src/components/BottomNavigation.js#L895

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios and android
| react-native          | 0.55
| react-native-paper    | 1.11.0
| node                  | 6
| npm or yarn           | 4.5

**Comment by ferrannp** [comment]
@satya164 what do you think? Probably it will have some problems with the animations?

**Comment by peacechen** [comment]
Another related issue, but with the label text size.  The container isn't quite big enough for text letters such as 'g' which extend below the baseline.
<img width="482" alt="things" src="https://user-images.githubusercontent.com/6295083/43208763-be8ba456-8ff0-11e8-879a-a3763646ae5f.png">

It would help to be able to configure the container size, icon size and label text size.

**Comment by satya164** [comment]
This should be automatic without having to specify size. PRs are welcome.

**Comment by peacechen** [comment]
@satya164  Are you referring to the icon size, or the tab bar size?

**Comment by satya164** [comment]
If you have a bigger icon and label size, everything should automatically adapt to that size. Shouldn't be hard to implement.

**Comment by peacechen** [comment]
As explained in the OP, the icon size is fixed at 24:
https://github.com/callstack/react-native-paper/blob/master/src/components/BottomNavigation.js#L895

The `label` and `labelContainer` styles use fixed sizes as well.   Looks like the labelContainer size is too small and truncates letters that extend below the baseline.

The labelContainer should not have a fixed height.  It will size automatically to the font size.

It would be great if the icon size and label font size were configurable via props.

**Comment by magworkss** [comment]
Unfortunately, component is not customisable...

**Comment by gauravmaini** [comment]
The issue still exists in MaterialBottomTabNavigator, the icon size is still hard coded to 24.
Here is the snippet from MaterialBottomTabView.tsx

        if (typeof options.tabBarIcon === 'string') {
          return (
            <MaterialCommunityIcons
              name={options.tabBarIcon}
              color={color}
              size={24}
              style={styles.icon}
            />
          );
        }

**Comment by obonyojimmy** [comment]
was this ever fixed ?
