### ISSUE TITLE
onPress FAB triggered when initially not visible

### ISSUE THREAD

**Issue by BenJeau** [callstack/react-native-paper#851]
### Current behaviour

When the visible property of the FAB is set to false, the FAB disappears, but the user can still click on the location where the FAB would have been and it would trigger the onPress of the FAB.

### Expected behaviour

When the visible property of the FAB is set to false, the FAB should disappear and the user should not be able to trigger the FAB.

### Code sample

I have tried replicating the issue on snack.expo.io, but I wasn't able to. Here is the repo of a sample react-native app with the issue https://github.com/BenJeau/react-native-paper-FAB-issue.

### Screenshots (if applicable)

You can see that the FAB is still there even though the FAB should not visible.
<img src="https://raw.githubusercontent.com/BenJeau/react-native-paper-FAB-issue/master/screenshot.jpg" width="300"/>

### What have you tried

I have created a new project from scratch to see if the other dependencies from my personal project would interfere with the FAB of react-native-paper. I was able to narrow the problem down. The issue is only present when you override the **style** of react-native-paper, in the sample project it's located in index.js.

The temporary solution for my project is to check in the onPress if the FAB is visible or not before executing the code in the onPress, but it creates a new issue since the screen has a scroll view and the user wouldn't be able to scroll when touching that part.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.58.4
| react-native-paper    | 2.11.1
| node                  | 11.8.0
| npm or yarn           | yarn

**Comment by ferrannp** [comment]
Fixed #858.

**Comment by Eirik-Skaara-Berg** [comment]
This issue appears to have reappeared. It is still present in version 5.12.3
