### ISSUE TITLE
Ripple button and icons 

### ISSUE THREAD

**Issue by zedart** [callstack/react-native-paper#947]
![screen](https://user-images.githubusercontent.com/29691281/54820756-7f8df980-4ca0-11e9-8638-b2176a36d180.PNG)
hi everyone
i have a probleme with ripple buttons it's outside of border
i had customise my button borderradius in style prop:
`import * as React from 'react';
import { StyleSheet } from 'react-native';
import { Button } from 'react-native-paper';

const MyLButton = () => (
  <Button
  mode="outlined"
  contentStyle= {styles.ButtunStyle}
  style= {styles.myButtunStyle}
  onPress={() => console.log('Pressed')}
  >
    Press me
  </Button>
);

const styles = StyleSheet.create({
  myButtunStyle: {
    elevation: 12,
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderBottomLeftRadius: 40,
  },
  ButtunStyle: {
    height: 80, width: 180,
    color: 'red', // don't change enything
  },

});`

and i cant have any icon 
PS. im a beginner so please be clair

**Comment by Trancever** [comment]
Hi @zedart Try to pass borderRadius also to `contentStyle` prop, it should fix the problem with ripple.

As for icons, did you link react-native-vector-icons? If not, please follow our getting [started guide](https://callstack.github.io/react-native-paper/getting-started.html)

**Comment by arkinem** [comment]
![image](https://user-images.githubusercontent.com/44735584/57547280-0df43280-7356-11e9-8352-6ab80d5ec83d.png)

Passing borderRadius to `style` and `contentStyle` doesn't solve the problem. Ripple still has a default value.

**Comment by mlukac-be** [comment]
@arkinem @zedart 

```javascript
export interface IButtonProps extends Omit<ButtonProps, 'children'> {
  text: string;
  textStyle?: TextProps;
}

export const Button = (props: IButtonProps) => (
  <PaperButton
    uppercase={false}
    {...props}
    style={[props.style]}
    theme={{ roundness: 50 }}
    contentStyle={props.contentStyle}
  >
    <Text style={[textStyle, props.textStyle]}>{props.text}</Text>
  </PaperButton>
)
```
Use ` theme={{ roundness: 50 }}`

**Comment by sathishu37** [comment]
> @arkinem @zedart
> 
> ```js
> export interface IButtonProps extends Omit<ButtonProps, 'children'> {
>   text: string;
>   textStyle?: TextProps;
> }
> 
> export const Button = (props: IButtonProps) => (
>   <PaperButton
>     uppercase={false}
>     {...props}
>     style={[props.style]}
>     theme={{ roundness: 50 }}
>     contentStyle={props.contentStyle}
>   >
>     <Text style={[textStyle, props.textStyle]}>{props.text}</Text>
>   </PaperButton>
> )
> ```
> 
> Use ` theme={{ roundness: 50 }}`
> 
> It's working for me. I'm using 2.15.2

Perfectly working
